name: Markdown Lint for ReadMe

on: [push, pull_request]

jobs:
  mdl-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.2
      - name: Run mdl
        uses: actionshub/markdownlint@v3.1.4